spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbootlevel1
    username: spring
    password: boot
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MariaDBDialect
  data:
    web:
      pageable:
        max-page-size : 20